"""add_department_agent_policy_links

Revision ID: 7ed610efc189
Revises: 27e7c8f10848
Create Date: 2026-07-11 06:58:28.457115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ed610efc189'
down_revision: Union[str, Sequence[str], None] = '27e7c8f10848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentpolicylink',
    sa.Column('agent_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agentconfig.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('agent_config_id', 'policy_id')
    )
    op.create_table('departmentpolicylink',
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('department_id', 'policy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departmentpolicylink')
    op.drop_table('agentpolicylink')
    # ### end Alembic commands ###
