"""add_database_connection

Revision ID: bc1b925344f3
Revises: d6e8383e3675
Create Date: 2026-07-09 12:16:02.342553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc1b925344f3'
down_revision: Union[str, Sequence[str], None] = 'd6e8383e3675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databaseconnection',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('db_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_dsn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('examples_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('databaseconnection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_databaseconnection_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('databaseconnection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_databaseconnection_company_id'))

    op.drop_table('databaseconnection')
    # ### end Alembic commands ###
