"""add_work_journal_entry

Revision ID: d6e8383e3675
Revises: 104c336aa939
Create Date: 2026-07-09 12:03:49.351998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6e8383e3675'
down_revision: Union[str, Sequence[str], None] = '104c336aa939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workjournalentry',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personnel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agentsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workjournalentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workjournalentry_personnel_id'), ['personnel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workjournalentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workjournalentry_personnel_id'))

    op.drop_table('workjournalentry')
    # ### end Alembic commands ###
